Feature/fixes on code
Mittelbots/Mittelbot pull request #1611
Opened 2023-08-07 23:05 UTC by wil92

## New

A fix in code that can improve the performance in the `messageUpdate` method.

## Changes & Bug fixes

I moved the implementation of the function `showResult` outside of the main method `messageUpdate`. With this, we are preventing the definition of the `showResult` function every time the main method is executed, and now this function is defined only one time when the file is imported and used in the main method when needed.

Type of change:
- [ ] This PR includes only documentation changes, no code change.
- [x] This PR introduces only smaller Bug fixes. Code should work as before and there's no new Dependencies
- [ ] This PR introduces some Breaking changes, which changes the way how some code works
- [ ] This PR introduces a new feature

2023-08-08 05:04 UTC, Mittelblut9 approved these changes
~~LGTM! Thanks 🙌~~

2023-08-08 05:06 UTC, Mittelblut9 requested changes
Wait, nvm. Please check the prettier format. Forgot to actually approve the workflows.

2023-08-08 07:25 UTC, Mittelblut9 commented
@wil92 can you merge the latest changes from the dev branch into yours? It Should fix the workflow errors.

2023-08-08 11:17 UTC, wil92 commented
@Mittelblut9 I rebase my fix on top of the dev branch, you can take a second look to it :smiley:

2023-08-08 16:51 UTC, Mittelblut9 commented
@wil92 Okay. I have tested it with an test fork. It should NOW work (hopefully)

2023-08-15 12:11 UTC, Mittelblut9 approved these changes

2023-08-15 12:11 UTC, merged